project_id = "brbgdvesterjvwduvsrf"

[functions.analyze-boq]
verify_jwt = false

[functions.analyze-charts]
verify_jwt = false

[functions.generate-timeline]
verify_jwt = false

[functions.analyze-costs]
verify_jwt = false

[functions.analyze-quotation]
verify_jwt = false