import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Award, Download, FileText, Shield } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { toast } from "sonner";

interface PricingCertificateProps {
  projectName: string;
  projectId: string;
  currency: string;
  totalItems: number;
  pricedItems: number;
  totalValue: number;
  categories: { name: string; value: number; count: number }[];
  isArabic: boolean;
  isDraft?: boolean;
}

export function PricingCertificate({
  projectName,
  projectId,
  currency,
  totalItems,
  pricedItems,
  totalValue,
  categories,
  isArabic,
  isDraft = true,
}: PricingCertificateProps) {
  const confidencePercentage = totalItems > 0 ? Math.round((pricedItems / totalItems) * 100) : 0;

  const exportPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(30, 64, 175);
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("PRICING CERTIFICATE", pageWidth / 2, 18, { align: "center" });
    doc.setFontSize(10);
    doc.text(isDraft ? "DRAFT" : "APPROVED", pageWidth / 2, 28, { align: "center" });
    doc.text(new Date().toLocaleDateString("en-US", { year: 'numeric', month: 'long', day: 'numeric' }), pageWidth / 2, 34, { align: "center" });

    // Project Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("Project Details", 14, 55);
    doc.setFontSize(10);
    doc.text(`Project: ${projectName}`, 14, 65);
    doc.text(`ID: ${projectId.slice(0, 8)}...`, 14, 72);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 79);

    // Summary Box
    doc.setDrawColor(200, 200, 200);
    doc.setFillColor(248, 250, 252);
    doc.rect(14, 88, pageWidth - 28, 30, 'FD');
    doc.setFontSize(12);
    doc.text("Pricing Summary", 20, 98);
    doc.setFontSize(10);
    doc.text(`Total Items: ${totalItems}`, 20, 107);
    doc.text(`Priced Items: ${pricedItems} (${confidencePercentage}%)`, 80, 107);
    doc.text(`Total Value: ${currency} ${totalValue.toLocaleString()}`, 150, 107);

    // Categories Table
    if (categories.length > 0) {
      autoTable(doc, {
        startY: 125,
        head: [["Category", "Items", `Value (${currency})`]],
        body: categories.map(cat => [
          cat.name,
          cat.count.toString(),
          cat.value.toLocaleString(),
        ]),
        theme: "grid",
        headStyles: { fillColor: [30, 64, 175] },
      });
    }

    // Status Stamp
    const finalY = (doc as any).lastAutoTable?.finalY || 160;
    doc.setFontSize(24);
    doc.setTextColor(isDraft ? 200 : 0, isDraft ? 150 : 128, isDraft ? 0 : 0);
    doc.text(isDraft ? "DRAFT" : "APPROVED", pageWidth / 2, finalY + 30, { align: "center" });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text("Generated by PMS - Project Management System", pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });

    doc.save(`pricing-certificate-${projectId.slice(0, 8)}.pdf`);
    toast.success(isArabic ? "تم تصدير الشهادة بنجاح" : "Certificate exported successfully");
  };

  return (
    <Card className="border-primary/20">
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-base">
          <Award className="w-5 h-5 text-primary" />
          {isArabic ? "شهادة التسعير" : "Pricing Certificate"}
          <Badge variant={isDraft ? "secondary" : "default"} className="text-xs">
            {isDraft ? (isArabic ? "مسودة" : "Draft") : (isArabic ? "معتمد" : "Approved")}
          </Badge>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        <div className="grid grid-cols-3 gap-3 text-center text-sm">
          <div>
            <p className="text-2xl font-bold text-primary">{totalItems}</p>
            <p className="text-xs text-muted-foreground">{isArabic ? "إجمالي البنود" : "Total Items"}</p>
          </div>
          <div>
            <p className="text-2xl font-bold text-green-600">{confidencePercentage}%</p>
            <p className="text-xs text-muted-foreground">{isArabic ? "نسبة الثقة" : "Confidence"}</p>
          </div>
          <div>
            <p className="text-lg font-bold">{currency} {totalValue.toLocaleString()}</p>
            <p className="text-xs text-muted-foreground">{isArabic ? "القيمة الإجمالية" : "Total Value"}</p>
          </div>
        </div>

        <Button onClick={exportPDF} className="w-full gap-2" variant="outline">
          <Download className="w-4 h-4" />
          {isArabic ? "تصدير شهادة PDF" : "Export PDF Certificate"}
        </Button>
      </CardContent>
    </Card>
  );
}
